excludes = [
    "*.lock",
    "*.patch",
    "package-lock.json",
    "go.mod",
    "go.sum",
    ".gitattributes",
    ".gitignore",
    ".gitmodules",
    ".hgignore",
    ".svnignore",
    "LICENSE",
]

[formatter.actionlint]
command = "actionlint"
excludes = []
includes = [".github/workflows/*.yml", ".github/workflows/*.yaml"]
options = []

[formatter.dos2unix]
command = "dos2unix"
excludes = []
includes = ["*"]
options = ["--keepdate"]

[formatter.keep-sorted]
command = "keep-sorted"
excludes = []
includes = ["*"]
options = []

[formatter.nixfmt]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.ruff-format]
command = "ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["format"]

[formatter.shellcheck]
command = "shellcheck"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = []

[formatter.shfmt]
command = "shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-w", "-i", "2", "-s"]
